### ISSUE TITLE
Feature Image and Author: Wire goes ZuriHac Post

### ISSUE THREAD

**Issue by android10** [wireapp/wireapp.github.io#6]
Regarding this live blog post in our engineering blog:
https://wire.engineering/haskell/events/2020/06/18/zurihac.html

**There is no feature image, which is a requirement to keep the blog's user interface attractive and consistent:**

![no_feature_picture](https://user-images.githubusercontent.com/1360604/86008371-f4f68700-ba18-11ea-85f9-2b607887bc5a.png)

**Feature image should fit this size: 500x750**

An example can be found here:
https://github.com/wireapp/wireapp.github.io/blob/master/assets/images/posts/organization_culture_humanity_featured.jpg

Blog post file should point to the image:
```
---
layout: post
...
image: assets/images/posts/organization_culture_humanity_featured.jpg
...
---
```

**Multi-author is not supported although it would be also a "nice to have" to add one, just as an entry point to have someone reachable in case someone wants to provide specific feedback or ask questions about the article itself**

Ping @fisx, @arianvp, @mheinzel

**Comment by mheinzel** [comment]
Last year we could have used a picture of the beautiful lake Zurich, but this year it doesn't seem fitting.

We can probably use the conference logo? https://github.com/zfoh/zfoh.ch/blob/master/images/zurihac2020/header-logo.png

**Comment by android10** [comment]
@mheinzel I'm totally fine, this is something that you have to decide. Whatever fits the best. 
It is mostly a cosmetic change in order to keep the UI consistent and attractive. 
Maybe send a PR?

**Comment by fisx** [comment]
i made a random screenshot with discord on it.  Hopefully free of IPR issues, and the equivalent of an image of lake zurich.  :-)

**Comment by fisx** [comment]
(feel free to change it again if you think this can be improved, i won't be offended :))
